name: Autograding Tests
on:
  - push
  - workflow_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Delete Makefile
        run: rm -f Makefile
      - name: Download Makefile
        run: curl -o Makefile https://raw.githubusercontent.com/uofl-russell/auto_grader_test_files/main/hello_github/makefile
      - name: A command test
        id: a-command-test
        uses: education/autograding-command-grader@v1
        with:
          test-name: A command test
          command: make clean
          timeout: 10
          max-score: 30
      - name: A command test
        id: b-command-test
        uses: education/autograding-command-grader@v1
        with:
          test-name: A command test
          command: make test
          timeout: 10
          max-score: 70          
      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          A-COMMAND-TEST_RESULTS: "${{steps.a-command-test.outputs.result}}"
          B-COMMAND-TEST_RESULTS: "${{steps.b-command-test.outputs.result}}"          
        with:
          runners: a-command-test,b-command-test